# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.common.exceptions import UnexpectedAlertPresentException
import time


def test_register():
    driver = webdriver.Chrome()
    driver.get("http://39.99.209.15:8081/bike/login/loginhtml")
    driver.set_window_size(1382, 784)
    driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
    driver.find_element(By.ID, "register_userName").click()
    driver.find_element(By.ID, "register_userName").send_keys("dm48")
    driver.find_element(By.ID, "register_password").click()
    driver.find_element(By.ID, "register_password").send_keys("123456")
    driver.find_element(By.ID, "register_againpsd").click()
    driver.find_element(By.ID, "register_againpsd").send_keys("123456")
    try:
        driver.find_element(By.CSS_SELECTOR, ".btn-success:nth-child(11)").click()
    except UnexpectedAlertPresentException:
        print("UnexpectedAlertPresentException")
    print("test_register finished")
    driver.quit()
    
def test_login():
    driver = webdriver.Chrome()
    driver.get("http://39.99.209.15:8081/bike/login/loginhtml")
    driver.set_window_size(1382, 784)
    driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    driver.find_element(By.ID, "login_userName").click()
    driver.find_element(By.ID, "login_userName").send_keys("Ahmelie")
    driver.find_element(By.ID, "login_password").click()
    driver.find_element(By.ID, "login_password").send_keys("123456")
    try:
        driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(9)").click()
    except UnexpectedAlertPresentException:
        print("UnexpectedAlertPresentException")
    print("test_login finished")
    driver.quit()
    
def test_aduit():
    driver = webdriver.Chrome()
    driver.get("http://39.99.209.15:8081/bike/login/loginhtml")
    driver.set_window_size(1382, 784)
    driver.find_element(By.CSS_SELECTOR, "body > div:nth-child(8)").click()
    driver.find_element(By.ID, "longitude").click()
    driver.find_element(By.CSS_SELECTOR, "#long_point > div:nth-child(1)").click()
    driver.find_element(By.ID, "latitude").click()
    driver.find_element(By.CSS_SELECTOR, "#lati_point > div:nth-child(1)").click()
    driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(16)").click()
    driver.find_element(By.ID, "score_result_a").click()
    driver.find_element(By.ID, "score_result_a").send_keys("30")
    driver.find_element(By.ID, "score_result_b").click()
    driver.find_element(By.ID, "score_result_b").send_keys("31")
    driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(21)").click()
    time.sleep(100)
    driver.find_element(By.CSS_SELECTOR, ".BMap_noprint:nth-child(18)").click()
    print("test_aduit finished")
    driver.quit()

def test_width():
    driver = webdriver.Chrome()
    driver.get("http://39.99.209.15:8081/bike/login/loginhtml")
    driver.set_window_size(1382, 784)
    driver.find_element(By.CSS_SELECTOR, "body > div:nth-child(10)").click()
    #driver.find_element(By.CSS_SELECTOR, ".inputBox").click()
    driver.find_element_by_xpath("//input[@type='file']").send_keys("C:\\Users\\asus3227\\Desktop\\mytest\\picture\\114.263116_30.591272_90_0.jpg")
    driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(8)").click()
    try:
        driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(10)").click()
    except UnexpectedAlertPresentException:
        print("UnexpectedAlertPresentException")
    #driver.switch_to.alert.accept()
    print("test_width finished")
    driver.quit()

def test_virescence():
    driver = webdriver.Chrome()
    driver.get("http://39.99.209.15:8081/bike/login/loginhtml")
    driver.set_window_size(1382, 784)
    driver.find_element(By.CSS_SELECTOR, "div:nth-child(11)").click()
    #driver.find_element(By.CSS_SELECTOR, ".inputBox").click()
    driver.find_element_by_xpath("//input[@type='file']").send_keys("C:\\Users\\asus3227\\Desktop\\mytest\\picture\\114.263116_30.591272_90_0.jpg")
    driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(8)").click()
    try:
        driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(10)").click()
    except UnexpectedAlertPresentException:
        print("UnexpectedAlertPresentException")
    #driver.switch_to.alert.accept()
    print("test_virescence finished")
    driver.quit()

def test_selfservice():
    driver = webdriver.Chrome()
    driver.get("http://39.99.209.15:8081/bike/login/loginhtml")
    driver.set_window_size(1382, 784)
    driver.find_element(By.CSS_SELECTOR, "div:nth-child(12)").click()
    #driver.find_element(By.CSS_SELECTOR, ".inputBox").click()
    driver.find_element_by_xpath("//input[@type='file']").send_keys("C:\\Users\\asus3227\\Desktop\\mytest\\picture\\114.263116_30.591272_90_0.jpg")
    driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(16)").click()
    try:
        driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(20)").click()
    except UnexpectedAlertPresentException:
        print("UnexpectedAlertPresentException")
    driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(22)").click()
    print("test_selfservice finished")
    driver.quit()
    
if __name__ == '__main__':
    test_register()
    test_login()
    test_aduit()
    test_width()
    test_virescence()
    test_selfservice()
